import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { Player, ImperativeHandle } from "@vimeo-player/react";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  // player ref
  const ref = React.useRef<ImperativeHandle>(null);
  // video id
  const [videoId, setVideoId] = React.useState("323783503");
  // control paused state
  const [paused, setPaused] = React.useState(false);
  // control muted
  const [muted, setMuted] = React.useState(false);

  async function seek(value: number) {
    if (!ref.current) return;
    const totalTime = await ref.current.getDuration();
    const getCurrentTime = await ref.current.getCurrentTime();
    await ref.current.seekTo(
      Math.min(Math.max(getCurrentTime + value, 0), totalTime)
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className={styles.vidContainer}>
          <Player
            video={videoId}
            ref={ref}
            paused={paused}
            autoplay={true}
            autopause={true}
            className={styles.vid}
            background={false}
            controls={false}
            dnt={false}
            language="en"
            loop={false}
            muted={true}
            speed={true}
            quality={"360p"}
            responsive={true}
            showByline={true}
            showPortrait={true}
            showTitle={true}
            onReady={() => {
              console.log("ready");
            }}
            onPlay={() => console.log("playing")}
            onPause={() => console.log("paused")}
          />
          <div className={styles.btnContainer}>
            <button onClick={() => seek(-10)}>-10s ⏪</button>
            <button onClick={() => seek(-5)}>-5s ◀️</button>
            <button onClick={() => seek(5)}>+5s ▶️</button>
            <button onClick={() => seek(10)}>+10s ⏩</button>
          </div>
          <div className={styles.btnContainer}>
            <button onClick={() => setPaused(true)}>Pause ⏸</button>
            <button onClick={() => setPaused(false)}>Play ▶️</button>
          </div>
        </div>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
